import tripledh
print('making a')
a = tripledh.TripleDH('akeypair')
print('making b')
b = tripledh.TripleDH('bkeypair',[a.get_fingerprint()])
print("adding b to a's trusties")
a.add_trusted(b.get_fingerprint())
print('handshaking with b in a')
a.handshake(b.get_pub_long_term(), b.get_pub_ephemeral(), tripledh.HandshakePos.high)
print('handshaking with a in b')
b.handshake(a.get_pub_long_term(), a.get_pub_ephemeral(), tripledh.HandshakePos.low)
print('getting secret')
print('secret in a is:',a.get_secret())
print('secret in b is:',b.get_secret())
a.make_sdata(tripledh.HandshakePos.high)
b.make_sdata(tripledh.HandshakePos.low)
print('sdata in a is :',a.get_sdata().hex())
print('sdata in b is :',b.get_sdata().hex())
